FROM node:16 as build

WORKDIR /app

COPY . /app

RUN npm ci
RUN npm run build:server

FROM node:16-alpine

ENV NODE_ENV=production

RUN npm install pm2 -g

WORKDIR /app
COPY --from=build /app/lib /app/lib
COPY --from=build /app/package.json .
COPY --from=build /app/package-lock.json .

RUN npm i

EXPOSE 9000

CMD ["pm2-runtime", "lib/server/index.js"]
